"""empty message

Revision ID: 07a00654bff2
Revises: None
Create Date: 2016-02-22 12:01:26.597433

"""

# revision identifiers, used by Alembic.
revision = '07a00654bff2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'owner_pkey')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owner')
    ### end Alembic commands ###
