"""empty message

Revision ID: dd8bb9b55960
Revises: 07a00654bff2
Create Date: 2016-02-22 17:50:00.042174

"""

# revision identifiers, used by Alembic.
revision = 'dd8bb9b55960'
down_revision = '07a00654bff2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelter', sa.Column('current_occupancy', sa.Integer(), nullable=True))
    op.add_column('shelter', sa.Column('maximum_capacity', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shelter', 'maximum_capacity')
    op.drop_column('shelter', 'current_occupancy')
    ### end Alembic commands ###
